### ISSUE TITLE
Info

### ISSUE THREAD

**Issue by tgiachi** [mheyer32/Breathless#1]
Fammi capire, stai sviluppando un gioco in asm ? Ma sei un grande! Complimenti davvero!! :) Stimo che qualcuno stia sviluppando ancora per amiga, io mi sono fermato al C per amiga

**Comment by mheyer32** [comment]
I'm sorry, but I don't speak italian. Could you repeat your question in english please?

And sorry for seeing your comment half a year later... I didn't know there's any interest in this project.
